import { defineConfig } from 'vite';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';

const here = (p) => fileURLToPath(new URL(p, import.meta.url));

/**
 * Writes dist/THIRD_PARTY_LICENSES.txt: every package that has code in the
 * bundle, with its version, licence and licence text. BlockSuite's own
 * packages (the AFFiNE monorepo, MIT) are listed by name under AFFiNE's
 * LICENSE-MIT once.
 */
function thirdPartyLicenses() {
  const pkgRoot = (id) => {
    let d = dirname(id.split('?')[0]);
    for (let i = 0; i < 12 && d && d !== dirname(d); i++, d = dirname(d)) {
      if (existsSync(join(d, 'package.json'))) return d;
    }
    return null;
  };
  return {
    name: 'third-party-licenses',
    generateBundle(_opts, bundle) {
      const roots = new Map();
      for (const chunk of Object.values(bundle)) {
        if (chunk.type !== 'chunk') continue;
        for (const [id, info] of Object.entries(chunk.modules)) {
          if (!info.renderedLength || id.startsWith('\0')) continue;
          const r = pkgRoot(id);
          if (r) roots.set(r, (roots.get(r) ?? 0) + info.renderedLength);
        }
      }
      const affine = [];
      const others = [];
      for (const r of roots.keys()) {
        let pkg;
        try {
          pkg = JSON.parse(readFileSync(join(r, 'package.json'), 'utf8'));
        } catch {
          continue;
        }
        if (!pkg.name || pkg.name === 'fxtxt-editor') continue;
        if (r.includes('/affine-src/')) {
          affine.push(`${pkg.name} ${pkg.version ?? ''} (${pkg.license ?? 'see LICENSE'})`);
          continue;
        }
        const lic = ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENCE', 'license', 'license.md', 'LICENSE-MIT']
          .map((f) => join(r, f))
          .find((f) => existsSync(f));
        const text = lic ? readFileSync(lic, 'utf8').trim() : '(no licence file in the package)';
        let license = typeof pkg.license === 'string' ? pkg.license : pkg.license?.type ?? '';
        // A package without a licence field is named by its licence file.
        if (!license && /Mozilla Public License Version 2\.0/.test(text)) license = 'MPL-2.0';
        if (!license && /^MIT License/m.test(text)) license = 'MIT';
        const repo = typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url ?? '';
        others.push({ name: pkg.name, version: pkg.version ?? '', license: license || 'UNKNOWN', repo, text });
      }
      affine.sort();
      others.sort((a, b) => a.name.localeCompare(b.name));
      const affineLicense = here('../../../fxtxt-bs/affine-src/LICENSE-MIT');
      const out = [
        'Third-party software in the filextext editor bundle (vendor/blocksuite).',
        'Generated by blocksuite/editor/vite.config.mjs at build time.',
        '',
        '='.repeat(78),
        'BlockSuite / AFFiNE (https://github.com/toeverything/AFFiNE, blocksuite/ subtree)',
        'Packages:',
        ...affine.map((a) => `  ${a}`),
        '',
        existsSync(affineLicense) ? readFileSync(affineLicense, 'utf8').trim() : 'MIT License, Copyright (c) 2022-present TOEVERYTHING PTE. LTD. and its affiliates.',
        '',
      ];
      for (const o of others) {
        out.push('='.repeat(78), `${o.name} ${o.version} — ${o.license}`, `Source: https://www.npmjs.com/package/${o.name}/v/${o.version}${o.repo ? ` (${o.repo})` : ''}`, '', o.text, '');
      }
      this.emitFile({ type: 'asset', fileName: 'THIRD_PARTY_LICENSES.txt', source: out.join('\n') });
      const summary = {};
      for (const o of others) summary[o.license] = (summary[o.license] ?? 0) + 1;
      console.log('third-party licences:', JSON.stringify(summary), 'blocksuite packages:', affine.length);
    },
  };
}

// Library build of the fxtxt editor (BlockSuite page editor, in-memory
// workspace). Output: dist/fxtxt-editor.{js,css} + dist/chunks/*.js, copied
// into the app repository's vendor/blocksuite/ by scripts/3-build-editor.sh.
//
// The app runs in a sandboxed, opaque-origin iframe whose CSP has no
// 'unsafe-eval' and no 'wasm-unsafe-eval'. Two aliases keep BlockSuite inside
// that:
//  - `shiki` -> src/shiki-facade.ts: a short language allow-list and the
//    JavaScript regex engine instead of the Oniguruma WebAssembly engine;
//  - `shiki/wasm` -> src/no-wasm.ts: the inlined Oniguruma binary is never
//    bundled.
export default defineConfig({
  plugins: [vanillaExtractPlugin({ unstable_mode: 'transform' }), thirdPartyLicenses()],
  esbuild: { target: 'es2022', legalComments: 'none' },
  resolve: {
    extensions: ['.ts', '.js'],
    alias: [
      { find: /^shiki$/, replacement: here('./src/shiki-facade.ts') },
      { find: /^shiki\/wasm$/, replacement: here('./src/no-wasm.ts') },
    ],
  },
  define: {
    'process.env.NODE_ENV': '"production"',
  },
  build: {
    target: 'es2022',
    outDir: 'dist',
    sourcemap: false,
    minify: true,
    cssCodeSplit: false,
    lib: {
      entry: 'src/index.ts',
      formats: ['es'],
      fileName: () => 'fxtxt-editor.js',
    },
    rollupOptions: {
      external: ['react/jsx-runtime', 'react', 'react-dom'],
      output: {
        assetFileNames: 'fxtxt-editor[extname]',
        chunkFileNames: 'chunks/[name]-[hash].js',
      },
      onwarn(w, d) {
        if (w.code && ['EVAL', 'SOURCEMAP_ERROR', 'CIRCULAR_DEPENDENCY'].includes(w.code)) return;
        d(w);
      },
    },
  },
});
